packages:
  # Include all packages in subdirectories
  - 'packages/*'
  # Exclude documentation or specific folders if needed
  - '!**/test/**'
allowBuilds:
  unrs-resolver: true
patchedDependencies:
  eslint-plugin-import-typescript@0.0.4: patches/eslint-plugin-import-typescript@0.0.4.patch
